'use client'

import { useState } from 'react'

const faqs = [
  {
    question: 'What is AIDEN?',
    answer:
      'AIDEN is an AI-powered landing page generator. You describe your product — name, audience, features, tone — and AIDEN writes professional, conversion-optimised copy and delivers a ready-to-publish HTML page in seconds.',
  },
  {
    question: 'How does it work?',
    answer:
      'Fill in a short form with details about your product. AIDEN sends that to Claude AI, which generates a complete landing page — headline, subheadline, feature descriptions, FAQ, and a call-to-action. The whole process takes under 60 seconds.',
  },
  {
    question: 'Can I use the generated pages commercially?',
    answer:
      'Yes. All copy and pages generated by AIDEN are yours to use however you like — on your website, in ads, in pitch decks, for client work, or anywhere else. There are no royalties or attribution requirements.',
  },
  {
    question: 'Do I need coding skills?',
    answer:
      'No coding required. The downloaded HTML file works out of the box. You can host it on Netlify, GitHub Pages, Vercel, or any static host in a few clicks — no developer needed.',
  },
  {
    question: 'What makes this different from ChatGPT?',
    answer:
      'ChatGPT gives you raw text you have to format yourself. AIDEN is purpose-built for landing pages: it outputs structured copy matched to a proven template, generates a live visual preview, and exports a ready-to-host HTML file — all in one click.',
  },
  {
    question: 'Can I cancel my Pro subscription?',
    answer:
      'Yes, you can cancel at any time from your account settings. Your Pro access continues until the end of the billing period. No hidden fees, no cancellation charges.',
  },
]

export default function FAQAccordion() {
  const [openIndex, setOpenIndex] = useState<number | null>(null)

  return (
    <section className="bg-gray-50 px-4 py-24 sm:px-6 lg:px-8">
      <div className="mx-auto max-w-3xl">
        <h2 className="text-3xl font-bold tracking-tight text-gray-900 text-center mb-12">
          Frequently asked questions
        </h2>
        <div className="space-y-3">
          {faqs.map((item, index) => {
            const isOpen = openIndex === index
            return (
              <div
                key={item.question}
                className="rounded-xl border border-gray-200 bg-white overflow-hidden"
              >
                <button
                  onClick={() => setOpenIndex(isOpen ? null : index)}
                  className="flex w-full items-center justify-between px-6 py-5 text-left"
                  aria-expanded={isOpen}
                >
                  <span className="text-sm font-semibold text-gray-900">{item.question}</span>
                  <span
                    className={`ml-4 flex-shrink-0 text-gray-400 transition-transform duration-200 ${isOpen ? 'rotate-180' : ''}`}
                    aria-hidden="true"
                  >
                    <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
                      <path d="M4 6l4 4 4-4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                    </svg>
                  </span>
                </button>
                {isOpen && (
                  <div className="px-6 pb-5">
                    <p className="text-sm text-gray-600 leading-relaxed">{item.answer}</p>
                  </div>
                )}
              </div>
            )
          })}
        </div>
      </div>
    </section>
  )
}
